"use client";
import Link from "next/link";
import { useEffect,useMemo,useState } from "react";
import { useParams } from "next/navigation";
import { authFetch } from "../../../../lib/api";
type Line={line_type:string;description:string;quantity:number;unit:string;unit_price:number};
const money=(v:any)=>new Intl.NumberFormat("fr-FR").format(Number(v||0))+" FCFA";
export default function EditProforma(){
 const params=useParams(),id=String(params.id),[customers,setCustomers]=useState<any[]>([]),[form,setForm]=useState<any>(null),[lines,setLines]=useState<Line[]>([]),[msg,setMsg]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{Promise.all([authFetch("/cement/customers").then(r=>r.json()),authFetch(`/cement/proformas/${id}`).then(r=>r.json())]).then(([cs,p])=>{setCustomers(Array.isArray(cs)?cs:[]);if(p.status!=="BROUILLON")setMsg("Cette proforma n'est plus modifiable.");setForm({customer_id:p.customer_id?String(p.customer_id):"",destination:p.destination||"",valid_until:p.valid_until?String(p.valid_until).slice(0,10):"",discount:Number(p.discount||0),tax_amount:Number(p.tax_amount||0),notes:p.notes||"",status:p.status});setLines((p.lines||[]).map((l:any)=>({line_type:l.line_type,description:l.description,quantity:Number(l.quantity),unit:l.unit,unit_price:Number(l.unit_price)})));});},[id]);
 const subtotal=useMemo(()=>lines.reduce((s,l)=>s+Number(l.quantity||0)*Number(l.unit_price||0),0),[lines]); const total=form?Math.max(subtotal-Number(form.discount||0)+Number(form.tax_amount||0),0):0;
 const upd=(i:number,k:keyof Line,v:any)=>setLines(a=>a.map((l,n)=>n===i?{...l,[k]:v}:l));
 async function save(){if(!form||form.status!=="BROUILLON")return;if(!form.customer_id)return setMsg("Choisis un client.");if(!lines.length||lines.some(l=>!l.description.trim()))return setMsg("Toutes les lignes doivent avoir une désignation.");setSaving(true);setMsg("");try{const r=await authFetch(`/cement/proformas/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,customer_id:Number(form.customer_id),lines:lines.map((l,i)=>({...l,sort_order:i}))})});const d=await r.json().catch(()=>({}));if(!r.ok)return setMsg(d.error||"Erreur modification.");window.location.href=`/ciment/proformas/${id}`;}finally{setSaving(false);}}
 if(!form)return <main className="p-8">Chargement...</main>;
 return <main className="min-h-screen bg-gray-50 p-4 text-black md:p-8"><div className="mx-auto max-w-5xl"><Link href={`/ciment/proformas/${id}`} className="mb-5 inline-block font-bold">← Retour</Link><h1 className="mb-6 text-3xl font-black">Modifier la proforma</h1>{msg&&<div className="mb-4 rounded bg-amber-50 p-3 font-bold">{msg}</div>}
 <section className="grid gap-3 rounded-2xl bg-white p-6 shadow md:grid-cols-3"><select className="rounded border p-3" value={form.customer_id} onChange={e=>setForm({...form,customer_id:e.target.value})}><option value="">Client</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="rounded border p-3" placeholder="Destination" value={form.destination} onChange={e=>setForm({...form,destination:e.target.value})}/><input type="date" className="rounded border p-3" value={form.valid_until} onChange={e=>setForm({...form,valid_until:e.target.value})}/></section>
 <section className="mt-5 rounded-2xl bg-white p-6 shadow"><div className="mb-4 flex justify-between"><h2 className="text-xl font-black">Articles / Prestations</h2><button onClick={()=>setLines([...lines,{line_type:"AUTRE",description:"",quantity:1,unit:"unité",unit_price:0}])} className="rounded bg-yellow-500 px-4 py-2 font-bold">+ Ligne</button></div>{lines.map((l,i)=><div key={i} className="mb-3 grid gap-2 rounded border p-3 md:grid-cols-12"><select className="rounded border p-2 md:col-span-2" value={l.line_type} onChange={e=>upd(i,"line_type",e.target.value)}><option>CIMENT</option><option>TRANSPORT</option><option>SABLE</option><option>LOCATION</option><option>AUTRE</option></select><input className="rounded border p-2 md:col-span-4" value={l.description} onChange={e=>upd(i,"description",e.target.value)}/><input type="number" step="0.001" className="rounded border p-2 md:col-span-2" value={l.quantity} onChange={e=>upd(i,"quantity",Number(e.target.value))}/><input className="rounded border p-2 md:col-span-1" value={l.unit} onChange={e=>upd(i,"unit",e.target.value)}/><input type="number" className="rounded border p-2 md:col-span-2" value={l.unit_price} onChange={e=>upd(i,"unit_price",Number(e.target.value))}/><button onClick={()=>lines.length>1&&setLines(lines.filter((_,n)=>n!==i))} className="rounded bg-red-50 p-2 text-red-600">×</button></div>)}</section>
 <section className="mt-5 grid gap-4 rounded-2xl bg-white p-6 shadow md:grid-cols-2"><textarea className="min-h-32 rounded border p-3" placeholder="Observation" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><div className="space-y-3 rounded bg-gray-100 p-4"><div className="flex justify-between"><span>Sous-total</span><b>{money(subtotal)}</b></div><label className="flex justify-between gap-3">Remise<input type="number" className="w-40 rounded border p-2" value={form.discount} onChange={e=>setForm({...form,discount:Number(e.target.value)})}/></label><label className="flex justify-between gap-3">Taxes<input type="number" className="w-40 rounded border p-2" value={form.tax_amount} onChange={e=>setForm({...form,tax_amount:Number(e.target.value)})}/></label><div className="flex justify-between border-t pt-3 text-xl"><b>TOTAL</b><b>{money(total)}</b></div><button disabled={saving||form.status!=="BROUILLON"} onClick={save} className="w-full rounded bg-black p-3 font-black text-white disabled:opacity-40">{saving?"Enregistrement...":"Enregistrer les modifications"}</button></div></section>
 </div></main>;
}